config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

project_name/urls.py
from {{ project_name }}  import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

home/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home/home.html'

users/views.py
from django.shortcuts import render

# Create your views here.

home/templates/home/home.html
{% extends 'base.html' %}

{% block container %}
    <h1>Home</h1>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django Template - {% block title %}Welcome{% endblock %}</title>

    {% block styles %}
        <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
    {% endblock %}

    {% block scripts %}
        <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>

{% include 'partials/navbar.html' %}

<div class="container mt-3">
    <div class="row">
        <div class="col-8">
            {% block container %}{% endblock %}
        </div>
        <div class="col-4">
            {% block aside %}{% endblock %}
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            {% block footer %}{% endblock %}
        </div>
    </div>
</div>

</body>
</html>

templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="">
            <img src="" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="">{{ user }}</a>
                </li>
            </ul>
        </div>
    </div>
</nav>